### ISSUE TITLE
How to launch the already Installed Apps in Roku device

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#15]
Team,

First I need to appreciate all your hard work on releasing this Rokuality. This is definitely going to rock the OTT automation in near future. We are studying this implementation, and will start using this once this is suitable for our need. 

I have a Query , if there is already Roku app is installed in the device, how to invoke that. Please help ?

**Comment by baclark774** [comment]
Glad you like what you see! 

In regard to launching an already installed app - currently it can only be done by attaching a capture card to the roku and the machine running the rokuality server and then providing the capture card indexes via your capabilities at driver start. The reason for this is that the underlying roku dev api's and roku webdriver prevent screen image capture and document evaluation for any channels that aren't a sideloaded dev channel.

But if you use a capture card we work around that limitation - the caveat being that when using a capture card, only the OCR and Image locators (By.Text, By.Image) will work and not the native based Roku Webdriver locators (RokuBy).

to launch an already installed app and use the capture card capabilities your capability setup would look like the following:

```
// id of the installed production channel to launch.
// can be found via curl http://your_roku_ip_address:8060/query/apps
capabilities.addCapability("App", "the id of the installed channel you wish to launch");

// the video and audio inputs of your capture card connected to your Roku
// can be found via:
// MAC: ~/Rokuality/dependencies/ffmpeg_v4.1 -f avfoundation -list_devices true -i ""
// WINDOWS: ~\Rokuality\dependencies\ffmpeg_win_v4.1\bin\ffmpeg.exe -list_devices true -f dshow -i dummy

capabilities.addCapability("VideoCaptureInput", "the video input of your capture card");
capabilities.addCapability("AudioCaptureInput", "the audio input of your capture card");
```

Under test most capture cards *should* work but we've tested against a few capture cards that are listed in the server readme page:
https://github.com/rokuality/rokuality-server#why-hdmi-to-usb-capture-cards

**Comment by rdhandapani88** [comment]
Amazing, it is workin fine now. I can launch the already installed app using capabilities.addCapability("App", "the id of the installed channel you wish to launch");

Closing the Issue.
