### ISSUE TITLE
Proxy Setup for the OTT devices

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#17]
Team,

As you all know, when the developer or QA testing the OTT devices, they mainly check the network logs for the installed or developed apps , to very if all the network requests are triggering correctly. Is there is any way in Rokuality in setting up the proxy in desired capabilities , like appium.

Eg:
capabilities.setCapability(CapabilityType.PROXY, seleniumProxy);

Right now we are not seeing any setCapabilities functionality. Also do you know any steps to capture the proxy logs when the scripts are running.

**Comment by baclark774** [comment]
So Roku doesn't make this easy like iOS/Android or the popular desktop browsers. But it can be done!

https://developer.roku.com/docs/developer-program/debugging/capturing-and-decrypting-ssl-packets.md

I use the wireshark method mentioned on their developer site for this type of backend traffic monitoring. And the traffic captured in the sniffer can then be programaticaly retrieved through their api and evaluated during the course of your automated run on the device. You would just have to set this up on your device before your automation run.

**Comment by rdhandapani88** [comment]
Thanks Closing the issue, as of now.
