### ISSUE TITLE
Testing capabilities for HDMI devices like LG TV, SAMSUNG TV, SetTOP boxes

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#26]
Team,

As we already have the capabilities for ROKU, xbox and playstations, do we have the capabilities for HDMI connected devices like smart tv and settop boxes (XFINITY). If then can you please share the capabilities (Desired caps) to invoke those devices. We have already procured the USB to HDMI capture card mentioned in the readme document. Currently we dont have any test for the HDMI devices in the Java framework. If then please share

**Comment by rdhandapani88** [comment]
I got it, HDMI devices are also working fine.

**Comment by baclark774** [comment]
Sorry for the delay. Yes you should be able to automate anything that has a hdmi input that can accept the capture card, and can accept either IR or bluetooth commands from the harmony hub. The playstation tests are just examples of doing exactly this. Simply replace the name capability with the name of your device as saved in your harmony hub and it should be good to go.

**Comment by rdhandapani88** [comment]
No Worries for the delay, you deserve some time off. Can you please mention some of HDMI remote commands. I can currently do DirectionDown, DirectionUP. What is the command for press OK or some other commands that we do in HDMI devices. We don't see any remote commands in the framework.

**Comment by baclark774** [comment]
The commands will be unique to each device. You can obtain them as follows:
`// get a list of available remote commands for your device
    String buttonOptions = driver.remote().getButtonOptions();
    System.out.println(buttonOptions);
    
    // send the desired button press to the device
    driver.remote().pressButton("DirectionUp");
    driver.remote().pressButton("Guide");
    driver.remote().pressButton("Select");`

**Comment by rdhandapani88** [comment]
Wow Awesome, Will give a try now. and let you know.
