### ISSUE TITLE
rokuality-server-1.2.6.jar is more stable than 1.2.8

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#33]
We are observing connectivity issues with the latest server 1.2.8, when the script is running it is getting disconnected from execution and execution stops .

**Comment by baclark774** [comment]
Can you share your activity logs to provide an example of when this happens to see what's going on? The overall reliability of the server from 1.2.6 to 1.2.8 shouldn't have any impact as there are no traffic impact changes. We haven't seen any impact on on production servers that run about 40,000 roku tests a day. But I'd need to see the logs and have a little more detail to get an understanding of what's going on. But the end result will most likely be a local networking issue. Have you tried running your tests on the rokuality device cloud at https://www.rokuality.com ? If you don't see any issues on our device cloud then it's def something with the local network.

**Comment by rdhandapani88** [comment]
Sure, Will post the log ,
