### ISSUE TITLE
Screenshot are getting blank screen when a video is playing in Roku

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#34]
We used the below method to capture the screenshot, when video is playing, but we are not getting the screenshot of Video. instead we are getting blank screen.

Method used to capture screenshot:
RokuDriver.screen().getImage()

![Video_Screenshot](https://user-images.githubusercontent.com/32144304/74848750-fcd54a80-5305-11ea-9aa4-bc358c97e413.png)

**Comment by baclark774** [comment]
An unfortunate limitation of image capture imposed by Roku while media is in flight to prevent piracy. Checkout the readme section for details but while video is playing you can use the getMediaInfo api and the getPageSource api to get details about the screen content and the media to verify playback is working properly.

**Comment by rdhandapani88** [comment]
Cool. Will check that now.
