### ISSUE TITLE
is there any option to send keys to HDMI devices

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#35]
I need to enter some search text in to HDMI devices. Do we have any options like ROKU to enter text in to HDMI devices.

**Comment by baclark774** [comment]
Unfortunately not. Each hdmi connected device could be totally different and in many cases there's no underlying api for control input. Example being a cable settop box. Which is why we have the harmony requirement for those devices. It's the only way to drive the user input for those devices that don't have apis to do so.
But what many of our users do in this case is create there own "sendKeys" method which is a matrix of whatever virtual keyboard their device happens to have. This can be done by keeping track of the starting location of the key and then mapping that to remote interactions that correlate to the alpha numeric keys of the virtual keyboard.

**Comment by rdhandapani88** [comment]
Hi have emulated the Keyboard using the below code. But it is working using Capture card.

This may be useful,

String[] line1 = new String[] {"Q","W","E","R","T","Y","U","I","O","P"};
			String[] line2 = new String[] {"A","S","D","F","G","H","J","K","L","back"};
			String[] line3 = new String[] {"Z","X","C","V","B","N","M","Number","space"};
			
			String searchText = "FIRE";
			int length = searchText.length();

			
			for(int i=0;i<length;i++) {
				

				char ch = searchText.charAt(i);
				if((Arrays.asList(line1).indexOf(""+ch+""))<0) {
					System.out.println("Not available in line 1");
					System.out.println("Remote Press to line 2");
					
					if((Arrays.asList(line2).indexOf(""+ch+""))<0) {
						System.out.println("Not available in line 2");
						System.out.println("Remote Press to line 3");
						
						if((Arrays.asList(line3).indexOf(""+ch+""))<0) {
							System.out.println("Not available in line 3");
							
						}else {
							System.out.println("Available in line 3");
							System.out.println(Arrays.asList(line3).indexOf(""+ch+"")); 
							
							PageBase.rokuDriver.remote().pressButton(RokuButton.DOWN_ARROW);
							Thread.sleep(2000);
							PageBase.rokuDriver.remote().pressButton(RokuButton.DOWN_ARROW);
							Thread.sleep(2000);
							
							for(int row3=0;row3<Arrays.asList(line3).indexOf(""+ch+"");row3++) {
								PageBase.rokuDriver.remote().pressButton(RokuButton.RIGHT_ARROW);
								Thread.sleep(2000);
								
							}
							
							PageBase.rokuDriver.remote().pressButton(RokuButton.SELECT);
							Thread.sleep(2000);
							
							for(int row3=0;row3<Arrays.asList(line3).indexOf(""+ch+"");row3++) {
								PageBase.rokuDriver.remote().pressButton(RokuButton.LEFT_ARROW);
								Thread.sleep(2000);
								
							}
							
							PageBase.rokuDriver.remote().pressButton(RokuButton.UP_ARROW);
							Thread.sleep(2000);
							PageBase.rokuDriver.remote().pressButton(RokuButton.UP_ARROW);
							Thread.sleep(2000);
						}
					}else {
						System.out.println("Available in line 2");
						System.out.println(Arrays.asList(line2).indexOf(""+ch+"")); 
						
						PageBase.rokuDriver.remote().pressButton(RokuButton.DOWN_ARROW);
						Thread.sleep(2000);
						
						for(int row2=0;row2<Arrays.asList(line2).indexOf(""+ch+"");row2++) {
							PageBase.rokuDriver.remote().pressButton(RokuButton.RIGHT_ARROW);
							Thread.sleep(2000);
							
						}
						
						PageBase.rokuDriver.remote().pressButton(RokuButton.SELECT);
						Thread.sleep(2000);
						
						for(int row2=0;row2<Arrays.asList(line2).indexOf(""+ch+"");row2++) {
							PageBase.rokuDriver.remote().pressButton(RokuButton.LEFT_ARROW);
							Thread.sleep(2000);
							
						}
						
						PageBase.rokuDriver.remote().pressButton(RokuButton.UP_ARROW);
						Thread.sleep(2000);
					}
					
				}else {
					System.out.println("Available in line 1");
					System.out.println(Arrays.asList(line1).indexOf(""+ch+"")); 
					
					for(int row1=0;row1<Arrays.asList(line1).indexOf(""+ch+"");row1++) {
						PageBase.rokuDriver.remote().pressButton(RokuButton.RIGHT_ARROW);
						Thread.sleep(2000);
						
					}
					
					PageBase.rokuDriver.remote().pressButton(RokuButton.SELECT);
					Thread.sleep(2000);
					
					for(int row1=0;row1<Arrays.asList(line1).indexOf(""+ch+"");row1++) {
						PageBase.rokuDriver.remote().pressButton(RokuButton.LEFT_ARROW);
						Thread.sleep(2000);
						
					}
				}
				
				
				
			}

**Comment by rdhandapani88** [comment]
Closing the issue now
