### ISSUE TITLE
Capabilities to Automate Samsung TV 

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#40]
Hi Team,
We know with this current rokuality, we can automate Android TV, and Apple Tv, which is HDMI. But We have a requirement to automate Samsung TV , which has Tizen OS, do we have any possibilities to automate Samsung TV. If then can u please let us know the capabilities and possible tools to do that. It will be really helpful.

**Comment by rokualitysupport** [comment]
latest version of the rokuality app now supports automating samsung tizen tv. see readme for details.
