### ISSUE TITLE
What happen to Rokuality Server....we are not seeing the project active

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#43]
Dear Team,

What happen to this Rokuality project, we are not seeing the server download ? are we continuing this project ?

Regards,

**Comment by baclark774** [comment]
Hello, the legacy rokuality server was deprecated and has been replaced into a new standalone app for mac and windows that also includes a full test builder/debugger. You can download the app at https://www.rokuality.com/download

From the launch window click the 'start server' button.

**Comment by rdhandapani88** [comment]
Awesome, thanks for the update. I was worried, that I may miss the wonderful solution.
