### ISSUE TITLE
Quick Question - Will this new Rokuality server dmg supports HDMI drivers as well

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#47]
Team,

Will this new Rokuality server dmg supports HDMI drivers as well ? like the old server or it is specifically for Roku and XBox ?

**Comment by rokualitysupport** [comment]
HDMI device support is planned for Q1 of 2021

https://www.rokuality.com/roadmap

**Comment by rokualitysupport** [comment]
Latest rokuality 1.3.0 includes hdmi driver support with a vastly improved encoder approach. See the readme for details.
