### ISSUE TITLE
Issue with findElement 

### ISSUE THREAD

**Issue by Diptimayee1993** [rokuality/rokuality-java#53]
Hi ,
1: I tried installing a app(LifeOK) other than your demo app (Clock). it is not getting installed .

2: With demo app also find Element is not working only app is getting installed and other tests getting failed.
3: For remote operation one permission popup is appearing on screen which is asking to accept and reject.

Attached Log : https://drive.google.com/file/d/1tOQQxJYJcgxxay87ULha-jO7Pp49anMi/view?usp=sharing

[https://drive.google.com/file/d/1tOQQxJYJcgxxay87ULha-jO7Pp49anMi/view?usp=sharing](url)

Please have a look & Provide some solutions.

Thanks and Regards
Diptimayee Beura

**Comment by rokualitysupport** [comment]
For tizen you need to first authorize the remote before remote control commands can be sent to it. See the readme section "Sending remote control commands to the device - Tizen TV" which will show you how to do this in code or via the test builder UI. Once you authorize you'll get back an api token which you can use as a "DeviceAPIToken" capability with the token value going forward.
