### ISSUE TITLE
Vizio TV Automation Support

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#59]
Dear Team,

Thanks for Fixing Samsung TV and LG Web os Automation. Do we have support for Vizio TV ? Some of our applications are developed for Vizio TV as well. If there is any way, kindly suggest,

**Comment by rokualitysupport** [comment]
Hello, we currently don't offer support for Vizio TV but it's on our roadmap for the 2nd quarter of this year. https://www.rokuality.com/roadmap

You can check our releases regularly and see when it's been included. https://www.rokuality.com/download

**Comment by rokualitysupport** [comment]
Vizio tv support is now available as of Rokuality version 1.3.5

https://www.rokuality.com/download
https://www.rokuality.com/vizio-device-automation
