### ISSUE TITLE
Screenshot capabilities for Samsung TV

### ISSUE THREAD

**Issue by rdhandapani88** [rokuality/rokuality-java#63]
Team,

How we can capture the screenshots from TV's, do we have any option. I see, "Getting screen artifacts:"

 // ROKU, TIZEN TV, and LG webOS ONLY
    // get the xml/html page markup
    rokuDriver.screen().getPageSource();

Will this will help to get the screen shot from Samsung and LG TV. Please help

**Comment by rokualitysupport** [comment]
Hello, the following methods will return either the full screen image or a specified screen sub image for any device:

// get the screen image
driver.screen().getImage();

// get the screen sub image from starting x,y with width/height
driver.screen().getImage(1, 1, 300, 300);

**Comment by rdhandapani88** [comment]
Thanks Team, Closing this issue for now.
